services:
  mongodb:
    image: mongo
    container_name: mongo-local
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    # command: ["mongod", "--replSet", "rs0", "--keyFile", "/data/configdb/keyfile"]
    volumes:
      - mongo_data:/data/db
      # - ./mongodb-keyfile:/data/configdb/keyfile

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: express123
    depends_on:
      - mongodb

volumes:
  mongo_data:
